[project]
name = "imagezebra-api-examples"
version = "0.1.0"
description = "Example code for the ImageZebra REST API"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
